

name: Python application

on:
  push:
    branches: [ "main" ]
  

permissions:
  contents: read
  #El write es necesario para que el workflow pueda subir los resultados de las pruebas a GitHub, como por ejemplo los artefactos o los resultados de las pruebas. y también para que pueda crear comentarios en los pull requests con los resultados de las pruebas o los errores encontrados.
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Test with pytest
      run: pytest

    - name: Ejecutar la app
      run: python app.py

    - name: Simular el despliegue
      run: echo "Desplegando la aplicación..."

    - name:  Construir la imagen de Docker
      run: docker build -t ghcr.io/ljbtorres-debug/ejercicio_docker_py_gtactions:2.1.0 .

    - name:  Iniciar sesión en GitHub Container Registry
      run: echo ${{ secrets.GHCR_PATH }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Subir la imagen de Docker a GitHub Container Registry
      run: docker push ghcr.io/ljbtorres-debug/ejercicio_docker_py_gtactions:2.1.0