

name: Python application

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4 # Actualizado a v4 que es más estable
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      # Asegúrate de que el nombre del archivo coincida exactamente con el de tu carpeta
      run: pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Construir la imagen de Docker
      run: docker build -t ghcr.io/${{ github.repository_owner }}/ejercicio_docker:1.0.0 .

    - name: Iniciar sesión en GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Subir la imagen
      run: docker push ghcr.io/${{ github.repository_owner }}/ejercicio_docker:1.0.0